version: '3.8'
name: ITQuiz

services:
  itquizbackend:
    image: mithrandier38/monitorsharing:itquizbackend
    platform: linux/amd64
    container_name: itquiz_backend_1.0
    ports:
      - "5154:5154"
    networks:
      - itquiz-network

  itquizfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: itquiz_frontend_1.0
    ports:
      - "3001:80"
    networks:
      - itquiz-network

networks:
  itquiz-network:
    driver: bridge
